---
title: "linearer_model_input"
output: html_notebook
---
Tobias
überarbeitet am 24.01.2020

#title: "linearer model input
#Ziel: model mit den master df variablen füttern
#Autor: "Tobias Lindenau"
#Datum des Erstellens: 18.01.2020


```{r}
#install.packages("Metrics")
#Bibliotheken
library(readr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(magrittr)
library(broom)
library(Metrics)

```

Einlesen der Daten
```{r}
# master df einlesen
master_df <- read.csv("master_df.csv")



master_df$Datum <- as.Date(master_df$Datum, format = "%Y-%m-%d")

#X Spalte loeschen
master_df$X<-NULL

```

Ja oder Nein Variablen als as.factor setzten
```{r}


master_df$Monat<-as.factor(master_df$Monat)
master_df$Weihnachtsmarkt<-as.factor(master_df$Weihnachtsmarkt)
master_df$Ferien<-as.factor(master_df$Ferien)
#master_df$KielerWoche<-as.factor(master_df$KielerWoche)
master_df$Wettercode<-as.factor(master_df$Wettercode)
master_df$Feiertag<-as.factor(master_df$Feiertag)
master_df$Temperaturklassen<-as.factor(master_df$Temperaturklassen)
master_df$nach_feiertag<-as.factor(master_df$nach_feiertag)
master_df$vor_feiertag<-as.factor(master_df$vor_feiertag)

```

Kiwo as double
```{r}
master_df$KielerWoche<-as.double(master_df$KielerWoche)
```

Na Value mit 0 ersetzten
```{r}
master_df <- master_df %>%
    mutate(KielerWoche = if_else(is.na(KielerWoche), 0, KielerWoche))

#von Merle eingefügt, damit alle NAs mit 0 ersetzt werden  klappte gerstern aber nicht heute
#master_df[is.na(master_df)] <- 0 
```


Modellgleichung
```{r}
mod1 <- lm(Gesamtumsatz ~ Ware_1, master_df)
mod2 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3, master_df)
mod3 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3 + Ware_4, master_df)
mod4 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3 + Ware_4 + Ware_5, master_df)
mod5 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6, master_df)
mod6 <- lm(Gesamtumsatz ~ Ware_1 + Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6 + as.factor(Temperaturklassen), master_df) #76% Testsieger
#mod6 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6 + Wochentag, master_df) #sehr kleine Verbesserung
mod7 <- lm(Gesamtumsatz ~ Ware_1 + Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6 + as.factor(Temperaturklassen), master_df) 
#mod7 <- lm(Gesamtumsatz ~ Ware_1+ Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6 + Wochentag + Ferien, master_df) #Sehr kleine Verschlechterung


summary(mod7)



```
```{r}
modx <- lm(Gesamtumsatz ~ as.factor(Feiertag) + Ware_2 + Ware_5 + Ware_6, master_df)
summary(modx)
```


```{r}
# Preparation of Model Results

rbind(glance(mod1), glance(mod2), glance(mod3), glance(mod4), glance(mod5), glance(mod6), glance(mod7))
```


modelle plotten
```{r}
#BEISPIEL
#lmTemp = lm(Pressure~Temperature, data = pressure) #Create the linear regression
plot(Gesamtumsatz, pch = 16, col = "blue") #Plot the results
#abline(lmTemp) #Add a regression line

#plot(master_df$Gesamtumsatz, pch = 16, col = "blue")
#abline(mod6)
```


```{r}
mod1 <- lm(Gesamtumsatz ~ Wochentag + Sonntag + Samstag + Monat + Weihnachtsmarkt + Ferien + Monat + Ware_1 + Ware_2 + Ware_3 + Ware_4 + Ware_5 + Ware_6 + weihnachtsfeiertag_25 + weihnachtsfeiertag_26 + weihnachtsfeiertag_27 + neujahrstage + KielerWoche, master_df)
summary(mod1)
```

